"""Constants ported from Arrietty-UE 0.13.1."""

VERSION = "0.13.1-up.10"
import os

STEERING_CONTROLLER_SERIAL = os.environ.get("ARRIETTY_STEERING_SERIAL", "")
RIDE_SURFACE_TAG = "SecretWorldRideSurface"
EYE_HEIGHT_METERS = 1.5
DEFAULT_LAP_LENGTH_METERS = 143.0
DEFAULT_MOVE_STEP_METERS = 0.5
DEFAULT_TURN_STEP_DEGREES = 5.0
TAKEOFF_SPEED_KMH = 20.0
WHEELBASE_METERS = 1.05
STEERING_GAIN = 0.50
STEERING_DEADZONE_DEGREES = 1.5
MAX_EFFECTIVE_STEERING_DEGREES = 15.0
BRAKE_GRADE_PERCENT = 3.0
SAMPLE_STALE_SECONDS = 1.25
HEART_RATE_STALE_SECONDS = 5.0
COAST_STOP_SPEED_KMH = 5.0
DEFAULT_WHEEL_STOP_SECONDS = 1.5
MIN_WHEEL_STOP_SECONDS = 0.75
MAX_WHEEL_STOP_SECONDS = 4.0

FLIGHT_EFFECTIVE_MASS_KG = 35.0
FLIGHT_GLIDE_RATIO = 30.0
FLIGHT_PROPELLER_EFFICIENCY = 0.80
FLIGHT_BEST_GLIDE_SPEED_KMH = 24.0
FLIGHT_STALL_SPEED_KMH = 18.0
FLIGHT_STALL_RECOVERY_SPEED_KMH = 20.5
FLIGHT_AIR_DENSITY_KG_PER_CUBIC_METER = 1.225
FLIGHT_WING_AREA_SQUARE_METERS = 15.0
FLIGHT_LIFT_CURVE_SLOPE_PER_DEGREE = 0.11
FLIGHT_POST_STALL_LIFT_FACTOR = 0.65
FLIGHT_POST_STALL_DRAG_COEFFICIENT = 0.12
FLIGHT_MAX_BANK_DEGREES = 25.0
FLIGHT_MAX_PITCH_DEGREES = 12.0
FLIGHT_CONTROL_STEP_DEGREES = 1.0
FLIGHT_PITCH_RATE_DEGREES_PER_SECOND = 28.0
FLIGHT_BANK_RATE_DEGREES_PER_SECOND = 55.0
FLIGHT_CONTROL_REFERENCE_SPEED_KMH = 24.0
FLIGHT_MIN_CONTROL_AUTHORITY = 0.20
FLIGHT_MAX_CONTROL_AUTHORITY = 1.75
FLIGHT_MAX_RUDDER_TURN_RATE_DEGREES = 10.0
FLIGHT_MAX_PROPELLER_THRUST_NEWTONS = 35.0
FLIGHT_GROUND_ROLLING_RESISTANCE = 0.012
FLIGHT_OVERSPEED_WARNING_KMH = 60.0

FLIGHT_TEST_PROPULSION_POWER_WATTS = 95.0
FLIGHT_TEST_PROPULSION_POWER_STEP_WATTS = 5.0
FLIGHT_MIN_TEST_PROPULSION_POWER_WATTS = 0.0
FLIGHT_MAX_TEST_PROPULSION_POWER_WATTS = 300.0
FLIGHT_PITCH_RATE_STEP_DEGREES_PER_SECOND = 2.0
FLIGHT_MIN_PITCH_RATE_DEGREES_PER_SECOND = 4.0
FLIGHT_MAX_PITCH_RATE_TUNING_DEGREES_PER_SECOND = 60.0
FLIGHT_BANK_RATE_STEP_DEGREES_PER_SECOND = 5.0
FLIGHT_MIN_BANK_RATE_DEGREES_PER_SECOND = 5.0
FLIGHT_MAX_BANK_RATE_TUNING_DEGREES_PER_SECOND = 120.0
FLIGHT_POSITIVE_CLIMB_MULTIPLIER = 10.0
FLIGHT_POSITIVE_CLIMB_MULTIPLIER_STEP = 1.0
FLIGHT_MIN_POSITIVE_CLIMB_MULTIPLIER = 1.0
FLIGHT_MAX_POSITIVE_CLIMB_MULTIPLIER = 20.0

FAN_MAXIMUM_SPEED_KMH = 30.0
FAN_STOPPED_THRESHOLD_KMH = 0.5
FAN_LEVEL_HYSTERESIS_KMH = 0.5
FAN_RESEND_SECONDS = 2.0
FAN_RESPONSE_TIMEOUT_SECONDS = 12.0
FAN_STOP_SEND_COUNT = 3
FAN_MAX_RESPONSES_PER_TICK = 8
FAN_LEVEL_COUNT = 6
FAN_UDP_HOST = "192.168.4.1"
FAN_UDP_PORT = 4210
VOICE_BRIDGE_HOST = "127.0.0.1"
VOICE_BRIDGE_PORT = 49000
